"""Pydantic v2 models for the Guru API.

All models inherit from GuruModel (extra="ignore", frozen=True) so they are
forward-compatible with API changes and immutable by default.

Models are generated from the Guru public Swagger spec. Re-generate with:
    python scripts/generate_models.py
"""

from guru_sdk.models._base import GuruModel
from guru_sdk.models._generated import (
    Answer,
    Card,
    CardAttachment,
    CardCollaborator,
    CardComment,
    CardCommentReply,
    CardInfo,
    CardSyncInfo,
    CardTemplate,
    CardVerifier,
    CardVerifiers,
    CollectionModel,
    Document,
    DocumentSearchResponse,
    DraftCard,
    EffectivePermissions,
    Folder,
    FolderCard,
    FolderItem,
    GroupedSourceConnection,
    KnowledgeAgent,
    KnowledgeAgentAccess,
    KnowledgeAgentConfig,
    NewCard,
    NewFolder,
    NLQSearchResponse,
    ObjectType,
    Page,
    SearchFacets,
    Source,
    Tag,
    TagCategory,
    Team,
    User,
    UserGroup,
    UserGroupAccess,
    UserGroupMember,
    WhoAmI,
)

__all__ = [
    "Answer",
    "Card",
    "CardAttachment",
    "CardCollaborator",
    "CardComment",
    "CardCommentReply",
    "CardInfo",
    "CardSyncInfo",
    "CardTemplate",
    "CardVerifier",
    "CardVerifiers",
    "CollectionModel",
    "Document",
    "DocumentSearchResponse",
    "DraftCard",
    "EffectivePermissions",
    "Folder",
    "FolderCard",
    "FolderItem",
    "GroupedSourceConnection",
    "GuruModel",
    "KnowledgeAgent",
    "KnowledgeAgentAccess",
    "KnowledgeAgentConfig",
    "NLQSearchResponse",
    "NewCard",
    "NewFolder",
    "ObjectType",
    "Page",
    "SearchFacets",
    "Source",
    "Tag",
    "TagCategory",
    "Team",
    "User",
    "UserGroup",
    "UserGroupAccess",
    "UserGroupMember",
    "WhoAmI",
]
